baseurl = "https://victorhugo.dev/"
title = "Victor Hugo"
theme = "hugo-coder"
languagecode = "pt"
defaultcontentlanguage = "pt"

[pagination]
    pagerSize = 20 # Default number of pages per page in pagination.

[markup.highlight]
    style = "github-dark"

[services]
[services.disqus]
    disqusShortname = "victorhugorch"

[params] # theme parameters
    author = "Victor Hugo Rocha" # Author's name.
    info = "Senior Software Engineer" # Author's job title or info.
    description = "Victor Hugo personal website" # Site description.
    keywords = "blog,developer,personal" # Site keywords.
    avatarurl = "https://i.imgur.com/p3bwx22.jpg" # Contain the path of the optionnal avatar in the static folder.

    colorScheme = "auto"
    hidecolorschemetoggle = false

    enableTwemoji = true

    # Custom CSS
    custom_css = []

    # Alignment of Mobile Menu items
    itemscentered = true

    # RTL support
    rtl = false

    snsShare = false # new add

    thumbnail = "images/tn.png" # default sns thumbnail

    # Multilanguage mode
    langseparator = "|" # Separates menus from language selectors when site is multilingual.

# Social links
[[params.social]]
    name = "Github"
    icon = "fa-brands fa-github fa-2x"
    weight = 1
    url = "https://github.com/victorhugoroch/"
[[params.social]]
    name = "LinkedIn"
    icon = "fa-brands fa-linkedin fa-2x"
    weight = 3
    url = "https://www.linkedin.com/in/victor-hugo-rocha-27738a8a/"
[[params.social]]
    name = "Instagram"
    icon = "fa-brands fa-instagram fa-2x"
    weight = 4
    url = "https://www.instagram.com/victorhugorch/"

[languages]
    [languages.en]
        languagename = "English" # The language name to be displayed in the selector.
        title = "Victor Hugo"

        # You can configure the theme parameter for each language.
        [languages.en.params]
        author = "Victor Hugo Rocha"
        info = "Senior Software Engineer"
        description = "Victor Hugo personal website"
        keywords = "blog,developer,personal"

    [languages.en.menu] # It is possible to change the menu too.

        [[languages.en.menu.main]]
        name = "About"
        weight = 1.0
        url = "about"

        [[languages.en.menu.main]]
        name = "Blog"
        weight = 2.0
        url = "posts"

    [languages.pt]
        languagename = "Portugues"
        title = "Victor Hugo"

        [languages.pt.params]
            author = "Victor Hugo Rocha"
            info = "Senior Software Engineer"
            description = "Site pessoal e blog"
            keywords = "blog,developer,desenvolvedor"

        [languages.pt.menu]

            [[languages.pt.menu.main]]
            name = "Sobre"
            weight = 1.0
            url = "about"

            [[languages.pt.menu.main]]
            name = "Blog"
            weight = 2.0
            url = "posts"
